name: Workflow to deploy on k8's or DigitalOcean

on:
  push:
    branches:
      - develop

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Crear .env file basado en DB_DRIVER
        run: |
          echo "DB_DRIVER=${{ secrets.DB_DRIVER }}" >> .env
          
          if [ "${{ secrets.DB_DRIVER }}" == "mysql" ]; then
            echo "DB_HOST=${{ secrets.MYSQL_DB_HOST }}" >> .env
            echo "DB_USER_NAME=${{ secrets.MYSQL_DB_USER_NAME }}" >> .env
            echo "DB_PASSWORD=${{ secrets.MYSQL_DB_PASSWORD }}" >> .env
            echo "DB_NAME=${{ secrets.MYSQL_DB_NAME }}" >> .env
            echo "DB_PORT=${{ secrets.MYSQL_DB_PORT }}" >> .env
          elif [ "${{ secrets.DB_DRIVER }}" == "postgres" ]; then
            echo "DB_HOST=${{ secrets.POSTGRES_DB_HOST }}" >> .env
            echo "DB_USER_NAME=${{ secrets.POSTGRES_DB_USER_NAME }}" >> .env
            echo "DB_PASSWORD=${{ secrets.POSTGRES_DB_PASSWORD }}" >> .env
            echo "DB_NAME=${{ secrets.POSTGRES_DB_NAME }}" >> .env
            echo "DB_PORT=${{ secrets.POSTGRES_DB_PORT }}" >> .env
          elif [ "${{ secrets.DB_DRIVER }}" == "mongo" ]; then
            echo "DB_HOST=${{ secrets.MONGO_DB_HOST }}" >> .env
            echo "DB_USER_NAME=${{ secrets.MONGO_DB_USER_NAME }}" >> .env
            echo "DB_PASSWORD=${{ secrets.MONGO_DB_PASSWORD }}" >> .env
            echo "DB_NAME=${{ secrets.MONGO_DB_NAME }}" >> .env
            echo "DB_PORT=${{ secrets.MONGO_DB_PORT }}" >> .env
          else
            echo "Error: DB_DRIVER no es válido"
            exit 1
          fi

      - name: Construir imagen del backend
        run: |
          docker build -t ppablo1999/proyecto_final_pablo:latest ./src

      - name: Autenticando en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Publicar imagen en Docker Hub
        run: |
          docker push ppablo1999/proyecto_final_pablo:latest
  
  deploy:
    needs: build-backend
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4
      
      - name: Crear base de datos y usuario si no existen
        run: |
          if [ "${{ secrets.DB_DRIVER }}" == "mysql" ]; then
            mysql -h ${{ secrets.MYSQL_DB_HOST }} -u ${{ secrets.MYSQL_DB_USER_NAME }} -p${{ secrets.MYSQL_DB_PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.MYSQL_DB_NAME }};"
            mysql -h ${{ secrets.MYSQL_DB_HOST }} -u root -p${{ secrets.MYSQL_DB_ROOT_PASSWORD }} -e "CREATE USER IF NOT EXISTS '${{ secrets.MYSQL_DB_USER_NAME }}'@'%' IDENTIFIED BY '${{ secrets.MYSQL_DB_PASSWORD }}'; GRANT ALL PRIVILEGES ON ${{ secrets.MYSQL_DB_NAME }}.* TO '${{ secrets.MYSQL_DB_USER_NAME }}'@'%'; FLUSH PRIVILEGES;"
          elif [ "${{ secrets.DB_DRIVER }}" == "postgres" ]; then
            PGPASSWORD=${{ secrets.POSTGRES_DB_PASSWORD }} psql -h ${{ secrets.POSTGRES_DB_HOST }} -U ${{ secrets.POSTGRES_DB_USER_NAME }} -c "CREATE DATABASE ${{ secrets.POSTGRES_DB_NAME }};"
            PGPASSWORD=${{ secrets.POSTGRES_DB_PASSWORD }} psql -h ${{ secrets.POSTGRES_DB_HOST }} -U postgres -c "CREATE USER ${{ secrets.POSTGRES_DB_USER_NAME }} WITH ENCRYPTED PASSWORD '${{ secrets.POSTGRES_DB_PASSWORD }}'; GRANT ALL PRIVILEGES ON DATABASE ${{ secrets.POSTGRES_DB_NAME }} TO ${{ secrets.POSTGRES_DB_USER_NAME }};"
          elif [ "${{ secrets.DB_DRIVER }}" == "mongo" ]; then
            mongo --host ${{ secrets.MONGO_DB_HOST }} --username ${{ secrets.MONGO_DB_USER_NAME }} --password ${{ secrets.MONGO_DB_PASSWORD }} --eval "db.getSiblingDB('${{ secrets.MONGO_DB_NAME }}').createCollection('init'); db.getSiblingDB('admin').runCommand({ createUser: '${{ secrets.MONGO_DB_USER_NAME }}', pwd: '${{ secrets.MONGO_DB_PASSWORD }}', roles: [{ role: 'readWrite', db: '${{ secrets.MONGO_DB_NAME }}' }] });"
          fi

      - name: Configurar despliegue basado en el recurso seleccionado
        run: |
          if [ "${{ secrets.RESOURCE }}" == "k8" ]; then
            echo "Desplegando en Kubernetes..."
            kubectl apply -f k8s.yaml
          elif [ "${{ secrets.RESOURCE }}" == "digital-ocean" ]; then
            echo "Desplegando en DigitalOcean Droplet..."
            ssh -o StrictHostKeyChecking=no ${{ secrets.DIGITAL_OCEAN_USER }}@${{ secrets.DIGITAL_OCEAN_HOST }} << 'EOF'
              cd /path/to/project
              echo "DB_DRIVER=${{ secrets.DB_DRIVER }}" > .env
              docker-compose down
              docker-compose up -d --build
            EOF
          else
            echo "Error: RESOURCE no es válido"
            exit 1
          fi