apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ppablo1999/proyecto_final_pablo:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_DRIVER
              value: "${DB_DRIVER}"
            - name: DB_HOST
              value: "${DB_HOST}"
            - name: DB_USER
              value: "${DB_USER}"
            - name: DB_PASSWORD
              value: "${DB_PASSWORD}"
            - name: DB_NAME
              value: "${DB_NAME}"
            - name: DB_PORT
              value: "${DB_PORT}"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: backend-config
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer