version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MY_DATABASE_DRIVER: "mysql"
      DB_HOST: db
      DB_USER_NAME: root
      DB_PASSWORD: rootpwd
      DB_NAME: database
      DB_PORT: 3310
    depends_on:
      - db
    ports:
      - 8081:3000
    restart: always
    networks:
      - my_network
  db:
    image: ppablo1999/mysql_pablo_var:latest
    container_name: db_mysql_pablo
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: database
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3310:3310
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network:
    driver: bridge