name: Workflow to deploy on k8's

on:
  push:
    branches:
      - modificador

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Crear .env file
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_USER_NAME=${{ secrets.DB_USER_NAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env

      - name: Construir imagen del backend
        run: |
          docker build -t ppablo1999/proyecto_final_pablo_var:latest ./src

      - name: Autenticando en dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Publicando imagen al dockerhub.....
        run: |
          docker push ppablo1999/proyecto_final_pablo_var:latest
  
  deploy-k8:
    needs: build-backend
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4
      
      - name: Configurar kubectl....
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.CLUSTER_KUBE_CONFIG_K8 }}
        with:
          args: apply -f k8s.yaml